export const COMFORT_THRESHOLDS = {
  TEMPERATURE: {
    MIN_ACCEPTABLE: 20.0,
    MIN_IDEAL: 23.0,
    TARGET: 24.0,
    MAX_IDEAL: 26.0,
    MAX_ACCEPTABLE: 28.0,
  },
  HUMIDITY: {
    MIN_ACCEPTABLE: 25.0,
    MIN_IDEAL: 35.0,
    TARGET: 50.0,
    MAX_IDEAL: 60.0,
    MAX_ACCEPTABLE: 70.0,
  },
  CO2: {
    EXCELLENT_MAX: 600,
    GOOD_MAX: 800,
    ACCEPTABLE_MAX: 1000,
    WARNING_THRESHOLD: 1000,
    CRITICAL_THRESHOLD: 1500,
  },
  LUX: {
    MIN_DESK_WORK: 300,
    TARGET_WORKSPACE: 500,
    OVERLIT_THRESHOLD: 1000,
  },
} as const;

export const SYSTEM_DEFAULTS = {
  VACANCY_GRACE_PERIOD_SEC: 60,
  VACANCY_CONFIRMATION_TIME_SEC: 300,
  UNACCOUNTED_POWER_THRESHOLD_W: 50,
  UNACCOUNTED_LOAD_PERSIST_SEC: 60,
  ANOMALY_PERCENTAGE_THRESHOLD: 15.0,
  GRID_EMISSIONS_FACTOR_KG_PER_KWH: 0.82,
  TARIFF_RATE_INR_PER_KWH: 8.0,
  SIMULATION_TICK_RATE_HZ: 1,
} as const;
