export const SIMULATION_DEFAULTS = {
  DEFAULT_TICK_RATE_HZ: 1,
  SPEED_MULTIPLIERS: [1, 2, 5, 10, 30, 60],
  DEFAULT_SPEED: 1,
  OUTDOOR_TEMP_C: 32.0,
  OUTDOOR_HUMIDITY_PCT: 65.0,
  OUTDOOR_CO2_PPM: 415.0,
  INITIAL_ROOM_TEMP_C: 24.0,
  INITIAL_ROOM_HUMIDITY_PCT: 50.0,
  INITIAL_ROOM_CO2_PPM: 450.0,
  INITIAL_ROOM_LUX: 500.0,
};

export const AUTOMATION_DEFAULTS = {
  VACANCY_GRACE_PERIOD_SEC: 60,
  VACANCY_CONFIRMATION_TIME_SEC: 300,
  PRE_COOL_MINUTES: 15,
  ANOMALY_PERCENTAGE_THRESHOLD: 15.0,
  UNACCOUNTED_POWER_THRESHOLD_W: 50.0,
  UNACCOUNTED_PERSISTENCE_SEC: 60,
  TARIFF_INR_PER_KWH: 8.0,
  GRID_CO2_KG_PER_KWH: 0.82,
};
