// ─── WebSocket Event Type Constants ───────────────────────
// All event types from spec §23

export const EventTypes = {
  // Room lifecycle
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_UPDATED: 'ROOM_UPDATED',
  ROOM_ARCHIVED: 'ROOM_ARCHIVED',

  // People & occupancy
  PERSON_ENTERED: 'PERSON_ENTERED',
  PERSON_EXITED: 'PERSON_EXITED',
  OCCUPANCY_CHANGED: 'OCCUPANCY_CHANGED',
  OCCUPANCY_STATE_CHANGED: 'OCCUPANCY_STATE_CHANGED',

  // Sensors
  SENSOR_READING_CREATED: 'SENSOR_READING_CREATED',
  ROOM_TELEMETRY_UPDATED: 'ROOM_TELEMETRY_UPDATED',

  // Devices
  DEVICE_REGISTERED: 'DEVICE_REGISTERED',
  DEVICE_UPDATED: 'DEVICE_UPDATED',
  DEVICE_STATE_CHANGED: 'DEVICE_STATE_CHANGED',
  DEVICE_COMMAND_REJECTED: 'DEVICE_COMMAND_REJECTED',

  // Automation
  AUTOMATION_ACTION: 'AUTOMATION_ACTION',
  VACANCY_TIMER_STARTED: 'VACANCY_TIMER_STARTED',
  VACANCY_TIMER_CANCELLED: 'VACANCY_TIMER_CANCELLED',

  // Alerts & Anomalies
  ALERT_CREATED: 'ALERT_CREATED',
  ALERT_UPDATED: 'ALERT_UPDATED',
  ANOMALY_DETECTED: 'ANOMALY_DETECTED',

  // Recommendations
  RECOMMENDATION_CREATED: 'RECOMMENDATION_CREATED',
  RECOMMENDATION_APPLIED: 'RECOMMENDATION_APPLIED',

  // Savings
  SAVINGS_SESSION_STARTED: 'SAVINGS_SESSION_STARTED',
  SAVINGS_EVENT_CREATED: 'SAVINGS_EVENT_CREATED',
  SAVINGS_UPDATED: 'SAVINGS_UPDATED',
  SAVINGS_SESSION_CLOSED: 'SAVINGS_SESSION_CLOSED',

  // Calibration
  CALIBRATION_STARTED: 'CALIBRATION_STARTED',
  CALIBRATION_PROGRESS: 'CALIBRATION_PROGRESS',
  CALIBRATION_COMPLETED: 'CALIBRATION_COMPLETED',

  // Scenarios
  SCENARIO_APPLIED: 'SCENARIO_APPLIED',
  SCENARIO_TRIGGERED: 'SCENARIO_TRIGGERED',

  // Simulation
  SIMULATION_TICK: 'SIMULATION_TICK',
  SIMULATION_PAUSED: 'SIMULATION_PAUSED',
  SIMULATION_RESUMED: 'SIMULATION_RESUMED',
} as const;

export type EventType = (typeof EventTypes)[keyof typeof EventTypes];
